<?php

//echo 'INDEXPHTML';

//echo __DIR__;
//print_r($_SERVER);
//require_once($_SERVER['DOCUMENT_ROOT'] . '..\application\Views\Index\Index.css');
//include(__DIR__ . '\Index.css');



ob_start();
echo '<style type="text/css">';
include(__DIR__ . '\Reg.css');

echo '</style>';

echo '<script type="text/javascript">';
include (__DIR__ . '\Reg.js');
echo '</script>';

$css_js = ob_get_contents();


ob_end_clean();



//<link rel = "stylesheet" href="application/Views/Index/Index.css">
//<link rel = "stylesheet" href="/Index.css">
//<script type="text/javascript" src = "/application/Views/Index/Index.js"></script>




?>

<!DOCTYPE html>
<html>

<head>

<?php echo $css_js; ?>
	<link href="/main/css/menu_main.css" rel="stylesheet"></link>
  	<link href="/main/css/menu_filtr.css" rel="stylesheet"></link>
	

</head>
<body>

<div>
</div>
<form action="/reg" method="get">
	<table>
    <tr>
        <td>Введите имя пользователя</td>
        <td><input name="user" type="text"></td>
    </tr>
    <tr>
        <td>Введите пароль</td>
        <td><input name="pass" type="password"></td>
        <td><input name="submit" type="submit"></td>
    <tr>
    </table>
    
</form>


<?php echo $this->modelData; ?>


</body>
</html>